CREATE TABLE [dbo].[Employees]
(
	[EmployeeId] [int] IDENTITY(1,1) NOT NULL,
	[FirstName] nvarchar(25),
	[LastName] nvarchar(25),
	[Email] nvarchar(25),
	[EmployeeGovernmentId] nvarchar(25),
	[HomePhoneNumber] nvarchar(25),
	[WorkPhoneNumber] nvarchar(25),
	[MovilPhoneNumber] nvarchar(25),
	[HireDate] datetime,
	[DateOfBirth] datetime,		
	[BiometricEmployeeId] nvarchar(25),
	[Salary] decimal,
	[EmployeTypeId] int,
	[EmployeeType] nvarchar(25), 
	[ResourceTypeId] int, 
	[ResourceType] nvarchar(25),
	[GenderId] int,
	[Gender] nvarchar(25), 
	[CurrencyTypeId] int, 
	[CurrencyType] nvarchar(25),
	[MaritalStatusId] int, 
	[MaritalStatus] nvarchar(25),
	[ManagerId] int, 
	[EmployeeTerminationTypeId] int,
	[EmployeeTerminationType] nvarchar(25),	
	[HomeStreetAddress1] nvarchar(100),
	[HomeStreetAddress2] nvarchar(100),
	[HomePostalCode] nvarchar(25),
	[HomeCity] nvarchar(25),
	[HomeStateProvince] nvarchar(25),
	[HomeCountryId] int,	
	[WorkStreetAddress1] nvarchar(100),
	[WorkStreetAddress2] nvarchar(100),
	[WorkPostalCode] nvarchar(25),
	[WorkCity] nvarchar(25),
	[WorkStateProvince] nvarchar(25),
	[WorkCountryId] int,  
	[DepartmentId] int,
	[Department] nvarchar(25),
	[CompanyId] int,
	[OrganizationId] int,
	[Organization] nvarchar(25),
	[Deleted] int
)
