CREATE TABLE [dbo].[Leads]
(
	[LeadsId] [int] IDENTITY(1,1) NOT NULL,
	[Subject] nvarchar (250),
	[Description] nvarchar (500),
	[Salutation] nvarchar (50),
	[First Name] nvarchar (50),
	[Last Name] nvarchar (50),
	[Job Title] nvarchar (50),
	[Company Name] nvarchar (50),
	[Home Phone] nvarchar (50),
	[Mobile Number] nvarchar (50),
	[Fax Number] nvarchar (50),
	[Other Phone] nvarchar (50),
	[Web Site] nvarchar (50),
	[Email] nvarchar (50),
	[StreeAddress1] nvarchar (250),
	[StreeAddress2] nvarchar (250),
	[City] nvarchar (50),
	[State/Province] nvarchar (50),
	[Zip/Postal Code] nvarchar (50),
	[CountryId] int,
	[LeadSourceId] int,
	[RatingId] int,
	[IndustryId] int,
	[Industry] nvarchar (25),
	[CurrencyId] int,
	[Currency] nvarchar (25),
	[Notes] nvarchar (500),
	[CampaingId] int,
	[OrganizationId] int,
	[Organization] nvarchar (50),
	[Deleted] int
)
